### ISSUE TITLE
Forslag til overlay data?

### ISSUE THREAD

**Issue by ellvtr** [GeoForum/veiledning03#1]
Jeg trenger data å legge over 3D modellen - se spec:
g. Legge til vektorflater lastet ned fra fks bygninger fra openstreetmap
h. Visualisere (deler) av terrenget med «extrudet» bygninger som 3D i nettleseren ved å bruke plugin: QGIS2ThreeJS

**Comment by alexanno** [comment]
Du kan jo bruke "buildings" fra OSM som vektorflater. Det finnes litt rundt forbi. Fks i Trondheim. Plugin finnes til QGIS (quick osm) som forenkler uthenting ganske mye.  

![image](https://cloud.githubusercontent.com/assets/1677418/7779542/a8abc632-00d5-11e5-888f-db59c3b7ee65.png)

![image](https://cloud.githubusercontent.com/assets/1677418/7779547/b99c4fca-00d5-11e5-9847-429564dd59ee.png)

![image](https://cloud.githubusercontent.com/assets/1677418/7779554/cdfb2540-00d5-11e5-9fbb-4beba5d2dee0.png)

![image](https://cloud.githubusercontent.com/assets/1677418/7779640/7aca8a86-00d6-11e5-9146-28ef8d7d974d.png)

![image](https://cloud.githubusercontent.com/assets/1677418/7779649/97251980-00d6-11e5-961e-d4056100809f.png)

![image](https://cloud.githubusercontent.com/assets/1677418/7779687/e3cdcdd6-00d6-11e5-8b86-d30d7f00b8f6.png)

**Comment by alexanno** [comment]
![image](https://cloud.githubusercontent.com/assets/1677418/7779932/7b059128-00d9-11e5-82f4-a2d994c682ed.png)

**Comment by ellvtr** [comment]
Takk - veldig bra! Har laget dette i seneste push for et øyeblikk siden.
